# ### client secret based keyvault access
# apiVersion: v1
# kind: Secret
# metadata:
#   name: secrets-store-creds
#   labels:
#     secrets-store.csi.k8s.io/used: "true" # Required label for the CSI driver to find the secret
# type: Opaque
# data:
#   clientid: {{ .Values.KeyVaultSync.ClientId | b64enc | quote }}
#   clientsecret: {{ .Values.KeyVaultSync.ClientSecret | b64enc | quote }}
# ###
### workload identity based keyvault access
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: {{ .Values.WorkloadIdentity.ClientName }}
#   annotations:
#     "azure.workload.identity/client-id": {{ .Values.WorkloadIdentity.ClientId }}
###
# ---
# apiVersion: secrets-store.csi.x-k8s.io/v1
# kind: SecretProviderClass
# metadata:
#   name: azure-notes-akv-sync
# spec:
#   provider: azure
#   secretObjects:
#   - secretName: app-iac-secrets
#     type: Opaque
#     data:
#       - objectName: connection-string
#         key: CONNECTION_STRING

#   parameters:
#     # clientID: {{ .Values.WorkloadIdentity.ClientId }} # Workload Identity Client ID
#     usePodIdentity: "false"                                                 # [REQUIRED] Set to "true" if using managed identities
#     useVMManagedIdentity: "false"                                           # [OPTIONAL] if not provided, will default to "false"
#     keyvaultName: {{ .Values.KeyVaultSync.KeyVaultName }}                   # [REQUIRED] the name of the key vault
#                                                                             #     az keyvault show --name contosoKeyVault5
#                                                                             #     the preceding command will display the key vault metadata, which includes the subscription ID, resource group name, key vault 
#     objects:  |
#       array:
#         - |
#           objectName: connection-string
#           objectType: secret

#     resourceGroup: {{ .Values.KeyVaultSync.ResourceGroupName }}             # [REQUIRED] the resource group name of the key vault
#     subscriptionId: {{ .Values.KeyVaultSync.SubscriptionId }}               # [REQUIRED] the subscription ID of the key vault
#     tenantId: {{ .Values.KeyVaultSync.TenantId }}                           # [REQUIRED] the tenant ID of the key vault
