hello: Welcome to SOPS! Edit this file as you please!
example_secret: ENC[AES256_GCM,data:wT6Z3X/ghiGxZ/98,iv:+g5uHwSYNSgNtuloSZ7o2diXwnyjV7gWKU5mLVvkCWQ=,tag:jFE9rOv1RRomr43I6t3ppQ==,type:str]
sops:
    azure_kv:
        - vault_url: https://workshop-cp-kv.vault.azure.net
          name: SOPS
          version: 6daf9fd6121a443ebe0ce86e03a19737
          created_at: "2025-04-14T08:27:16Z"
          enc: UZESQfO4j2TGiFkO30I1DUS6fVnVRxfE5fhDrFQ3FybNU_0U-gVEiTqOcwTeGW1uzvJOOvoxu7L7jtfVAH84xeKVrbXMuM1lrK0cV3y8Y05LS3YiVIGaPpy6ZqEGRZD_7PxYFkXWa9uuPkwdxjWL9i1p-4X2HWzZP4N44r0p_-iaclYAslnxygDwgDugEcU3KQjVf0ohC9LI0f7g5wCqNj1ACHc8xzCjRYg_r9Bcf6mv1nTt5ZBLB_WnC1JvE2hQcqxZZ-OINtk2i6kzpWprL28sQf4DVCgmu7ZOqb-EO-uGXDr_Xj6Fm7UAtbfSv-8jk09wsykNmtlQBEOb7WOE7A
    lastmodified: "2025-05-19T09:57:44Z"
    mac: ENC[AES256_GCM,data:Ctp8t0QByeEXN5wIfBTz6wBcBRERbPoVuFOMnTuSF7L8k/pX/FJ43xAzbiKem3WzYsNDlOh3oQAGg69ZgujlIv/S/mbjkeReeenQfiqhJwUeqLMUP8RhJHrTHWEPtn9wkUl7PtKXEN7VEp8pz8ZwLVzMbyfYrDN+w+7VfARm2YU=,iv:4cYwG4orpz9Dgj9KGa5z7shZEFe3uzs9ZK0CJ8eAsjw=,tag:ogwCdNeKTq2DOmK4oNq4mw==,type:str]
    encrypted_regex: .*_secret|.*_key
    version: 3.10.1
